# Project Information
site_name: CauchyChips
site_description: Site prépa
site_author: Le prince de sang-mêlé
site_url: https://cauchychips.github.io/
strict: false

# Repository
repo_name: 'cauchychips/cauchychips.github.io'
repo_url: 'https://github.com/cauchychips/cauchychips.github.io'
edit_uri: 'https://github.com/cauchychips/cauchychips.github.io'

# Copyright
copyright: 'pas de copyright tqt'

# Contents
nav:
  - Introduction:
    - Présentation: index.md
    - Symbols: intro/symbol.md
  - Informatique:
    - Présentation: contest/index.md
    - Exos d'implémentation:
      - C: contest/oi.md
      - Ocaml: contest/icpc.md
    - Langages:
      - Langages réguliers: contest/problems.md
      - Automates: contest/interaction.md
    - Graphes: contest/roadmap.md
    - Algorithmique: contest/resources.md
    - Programmation dynamique:
      - 读入、输出优化: contest/io.md
      - 分段打表: contest/dictionary.md
      - 常见错误: contest/common-mistakes.md
      - 常见技巧: contest/common-tricks.md
    - Misc: contest/problemsetting.md
  - Mathématiques:
    - 工具软件简介: tools/index.md
    - 代码编辑工具:
      - Vim: tools/editor/vim.md
      - Emacs: tools/editor/emacs.md
      - VS Code: tools/editor/vscode.md
      - Atom: tools/editor/atom.md
      - Eclipse: tools/editor/eclipse.md
      - Notepad++: tools/editor/npp.md
      - Kate: tools/editor/kate.md
      - Dev-C++: tools/editor/devcpp.md
      - CLion: tools/editor/clion.md
      - Geany: tools/editor/geany.md
      - Xcode: tools/editor/xcode.md
      - GUIDE: tools/editor/guide.md
      - Sublime Text: tools/editor/sublime.md
      - CP Editor: tools/editor/cpeditor.md
      - Code::Blocks: tools/editor/codeblocks.md
    - 评测工具: 
      - 评测工具简介: tools/judger/index.md
      - Arbiter: tools/judger/arbiter.md
      - Cena: tools/judger/cena.md
      - CCR Plus: tools/judger/ccr-plus.md
      - Lemon: tools/judger/lemon.md
    - 命令行: tools/cmd.md
    - 编译器: tools/compiler.md
    - WSL (Windows 10): tools/wsl.md
    - Special Judge: tools/special-judge.md
    - Testlib:
      - Testlib 简介: tools/testlib/index.md
      - 通用: tools/testlib/general.md
      - Generator: tools/testlib/generator.md
      - Validator: tools/testlib/validator.md
      - Interactor: tools/testlib/interactor.md
      - Checker: tools/testlib/checker.md
    - Polygon: tools/polygon.md
    - OJ 工具: tools/oj-tool.md
    - LaTeX 入门: tools/latex.md
    - Git: tools/git.md
  - Physique:
    - 语言基础简介: lang/index.md
    - C++ 基础:
      - Hello, World!: lang/helloworld.md
      - C++ 语法基础: lang/basic.md
      - 变量: lang/var.md
      - 运算: lang/op.md
      - 流程控制语句:
        - 分支: lang/branch.md
        - 循环: lang/loop.md
      - 高级数据类型:
        - 数组: lang/array.md
        - 结构体: lang/struct.md
        - 联合体: lang/union.md
        - 指针: lang/pointer.md
      - 函数: lang/func.md
      - 文件操作: lang/file-op.md
    - C++ 标准库:
      - C++ 标准库简介: lang/csl/index.md
      - STL 容器:
        - STL 容器简介: lang/csl/container.md
        - 迭代器: lang/csl/iterator.md
        - 序列式容器: lang/csl/sequence-container.md
        - 关联式容器: lang/csl/associative-container.md
        - 无序关联式容器: lang/csl/unordered-container.md
        - 容器适配器: lang/csl/container-adapter.md
      - STL 算法: lang/csl/algorithm.md
      - bitset: lang/csl/bitset.md
      - string: lang/csl/string.md
      - pair: lang/csl/pair.md
    - C++ 进阶:
      - 类: lang/class.md
      - 命名空间: lang/namespace.md
      - 值类别: lang/value-category.md
      - 重载运算符: lang/op-overload.md
      - 引用: lang/reference.md
      - 常量: lang/const.md
      - 新版 C++ 特性: lang/new.md
      - Lambda 表达式: lang/lambda.md
      - pb_ds:
        - pb_ds 简介: lang/pb-ds/index.md
        - 堆: lang/pb-ds/pq.md
        - 平衡树: lang/pb-ds/tree.md
      - 编译优化: lang/optimizations.md
    - C++ 与其他常用语言的区别: lang/cpp-other-langs.md
    - Pascal 转 C++ 急救: lang/pas-cpp.md
    - Python 速成: lang/python.md
    - Java 速成: lang/java.md
    - Java 进阶: lang/java-pro.md
  - Français:
    - 算法基础简介: basic/index.md
    - 复杂度: 
      - 复杂度简介: basic/complexity.md
      - 均摊复杂度: basic/amortized-analysis.md
    - 枚举: basic/enumerate.md
    - 模拟: basic/simulate.md
    - 递归 & 分治: basic/divide-and-conquer.md
    - 贪心: basic/greedy.md
    - 排序:
      - 排序简介: basic/sort-intro.md
      - 选择排序: basic/selection-sort.md
      - 冒泡排序: basic/bubble-sort.md
      - 插入排序: basic/insertion-sort.md
      - 计数排序: basic/counting-sort.md
      - 基数排序: basic/radix-sort.md
      - 快速排序: basic/quick-sort.md
      - 归并排序: basic/merge-sort.md
      - 堆排序: basic/heap-sort.md
      - 桶排序: basic/bucket-sort.md
      - 希尔排序: basic/shell-sort.md
      - 锦标赛排序: basic/tournament-sort.md
      - Tim 排序: basic/tim-sort.md
      - 排序相关 STL: basic/stl-sort.md
      - 排序应用: basic/use-of-sort.md
    - 前缀和 & 差分: basic/prefix-sum.md
    - 二分: basic/binary.md
    - 倍增: basic/binary-lifting.md
    - 构造: basic/construction.md
  - Anglais:
    - 搜索部分简介: search/index.md
    - DFS（搜索）: search/dfs.md
    - BFS（搜索）: search/bfs.md
    - 双向搜索: search/bidirectional.md
    - 启发式搜索: search/heuristic.md
    - A*: search/astar.md
    - 迭代加深搜索: search/iterative.md
    - IDA*: search/idastar.md
    - 回溯法: search/backtracking.md
    - Dancing Links: search/dlx.md
    - Alpha-Beta 剪枝: search/alpha-beta.md
    - 优化: search/opt.md
  - TIPE:
    - 动态规划部分简介: dp/index.md
    - 动态规划基础: dp/basic.md
    - 记忆化搜索: dp/memo.md
    - 背包 DP: dp/knapsack.md
    - 区间 DP: dp/interval.md
    - DAG 上的 DP: dp/dag.md
    - 树形 DP: dp/tree.md
    - 状压 DP: dp/state.md
    - 数位 DP: dp/number.md
    - 插头 DP: dp/plug.md
    - 计数 DP: dp/count.md
    - 动态 DP: dp/dynamic.md
    - 概率 DP: dp/probability.md
    - DP 优化:
      - 单调队列/单调栈优化: dp/opt/monotonous-queue-stack.md
      - 斜率优化: dp/opt/slope.md
      - 四边形不等式优化: dp/opt/quadrangle.md
      - 状态设计优化: dp/opt/state.md
    - 其它 DP 方法: dp/misc.md
  - Personnel:
    - 字符串部分简介: string/index.md
    - 字符串基础: string/basic.md
    - 标准库: string/lib-func.md
    - 字符串匹配: string/match.md
    - 字符串哈希: string/hash.md
    - 字典树 (Trie): string/trie.md
    - 前缀函数与 KMP 算法: string/kmp.md
    - Boyer–Moore 算法: string/bm.md
    - Z 函数（扩展 KMP）: string/z-func.md
    - 自动机: string/automaton.md
    - AC 自动机: string/ac-automaton.md
    - 后缀数组 (SA):
      - 后缀数组简介: string/sa.md
      - 最优原地后缀排序算法: string/sa-optimal-inplace.md
    - 后缀自动机 (SAM): string/sam.md
    - 后缀平衡树: string/suffix-bst.md
    - 广义后缀自动机: string/general-sam.md
    - 后缀树: string/suffix-tree.md
    - Manacher: string/manacher.md
    - 回文树: string/pam.md
    - 序列自动机: string/seq-automaton.md
    - 最小表示法: string/minimal-string.md
    - Lyndon 分解: string/lyndon.md
    - Main–Lorentz 算法: string/main-lorentz.md

# Theme
theme:
  name: material
  custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'fr'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'


extra_javascript:
  #- js/config.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - css/extra.css

markdown_extensions:
  - document-offsets-injection:
      # debug: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

